services:
  postgres-service:
    image: postgres
    container_name: postgres-service
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: xml_db
      POSTGRES_USER: xml
      POSTGRES_PASSWORD: k1234
    ports:
      - '5432:5432'
    expose:
      - '5432'
    healthcheck:
      test: "exit 0"
    restart: unless-stopped

  pgadmin4:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: unless-stopped

    ports:
      - "8889:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ouss@gmail.com
      PGADMIN_DEFAULT_PASSWORD: azer
    volumes:
      - pgadmin_data:/var/lib/pgadmin













volumes:
  postgres_data:
  pgadmin_data:










#  discovery-service:
#    build: ./Discovery
#    container_name: discovery-service
#    ports:
#      - "8761:8761"
#    expose:
#      - "8761"
#    healthcheck:
#      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
#      interval: 10s
#
#  config-service:
#    build: ./Config
#    container_name: config-service
#    ports:
#      - "9999:9999"
#    expose:
#      - "9999"
#    environment:
#      - DISCOVRY_URL=http://discovery-service:8761/eureka
#    healthcheck:
#      test: ["CMD", "curl", "-f", "http://localhost:9999/actuator/health"]
#      interval: 10s
#    depends_on:
#      discovery-service:
#        condition: service_healthy
#
#  etudiant-service:
#    build: ./Etudiant
#    container_name: etudiant-service
#    ports:
#      - "8090:8090"
#    expose:
#      - "8090"
#    environment:
#      - DISCOVERY_URL=http://discovery-service:8761/eureka
#      - CONFIG_URL=http://config-service:9999
#
#    depends_on:
#        config-service:
#            condition: service_healthy
#    healthcheck:
#        test: ["CMD", "curl", "-f", "http://localhost:8090/actuator/health"]
#        interval: 10s
#
#  liver-service:
#    build: ./liver
#    container_name: liver-service
#    ports:
#      - "8091:8091"
#    expose:
#      - "8091"
#    environment:
#      - DISCOVERY_URL=http://discovery-service:8761/eureka
#      - CONFIG_URL=http://config-service:9999
#
#    depends_on:
#        config-service:
#            condition: service_healthy
#    healthcheck:
#        test: ["CMD", "curl", "-f", "http://localhost:8091/actuator/health"]
#        interval: 10s
#
#  emprunt-service:
#    build: ./emprunter
#    container_name: emprunt-service
#    ports:
#      - "8082:8082"
#    expose:
#      - "8082"
#    environment:
#      - DISCOVERY_URL=http://discovery-service:8761/eureka
#      - CONFIG_URL=http://config-service:9999
#
#    depends_on:
#        config-service:
#            condition: service_healthy
#        liver-service:
#            condition: service_healthy
#        etudiant-service:
#            condition: service_healthy
#    healthcheck:
#        test: ["CMD", "curl", "-f", "http://localhost:8082/actuator/health"]
#        interval: 10s
#
#  gateway:
#    build: ./gateway
#    container_name: gateway-service
#    ports:
#      - "8888:8888"
#    expose:
#      - "8888"
#    environment:
#      - DISCOVERY_URL=http://discovery-service:8761/eureka
#      - CONFIG_URL=http://config-service:9999
#    depends_on:
#        emprunt-service:
#          condition: service_healthy
#        liver-service:
#          condition: service_healthy
#        etudiant-service:
#          condition: service_healthy
